# Site settings
title: Christian Eiselt

avatar: https://avatars.githubusercontent.com/christianeiselt

theme: jekyll-theme-modernist

collections:
  pages:
    output: true
    permalink: /:path/

permalink: pretty

plugins:
- jemoji
